version: "3.7"
services:
  postgres:
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"
  redis:
    image: redis:7.0.9-alpine
    ports:
      - "${REDIS_PORT}:6379"
    command:
      ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  influxdb:
    image: influxdb:2.6.1-alpine
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG_NAME}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET_NAME}
