version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - "${PG_PORT}:${PG_PORT}"
  redis:
    image: redis:7.0.9-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command:
      ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  # django:
  #   container_name: django
  #   build: .
  #   depends_on:
  #     - postgres
  #     - redis
  #   ports:
  #     - "3000:3000"
  #   command: >
  #     bash -c "python manage.py runserver 0.0.0.0:3000"
  # tg_bot:
  #   container_name: tg_bot
  #   build: .
  #   depends_on:
  #     - postgres
  #     - redis
  #   command: >
  #     bash -c "python manage.py bot"

