version: "3.7"
services:
  postgres:
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - "${PG_PORT}:${PG_PORT}"
  redis:
    image: redis:7.0.9-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command:
      ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  influxdb:
    image: influxdb:2.6.1-alpine
    ports:
      - "${INFLUXDB_PORT}:${INFLUXDB_PORT}"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
