version: "3.7"
services:
  postgres:
    image: postgres:15.2-alpine
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE_NAME}
  redis:
    image: redis:7.0.9-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command:
      ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
