# Generated by Django 4.1 on 2023-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('first_ip', models.CharField(max_length=16)),
                ('requests', models.IntegerField(default=0)),
                ('ans_added', models.IntegerField(default=0)),
                ('ans_got', models.IntegerField(default=0)),
                ('subsription_lvl', models.CharField(default='blank', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
