# Generated by Django 4.1 on 2023-03-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('interval', models.CharField(max_length=5)),
                ('period', models.IntegerField(default=3)),
                ('infelicity', models.IntegerField(default=1)),
                ('value', models.IntegerField(default=0)),
                ('last_value', models.IntegerField(default=0)),
                ('side', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
