# Generated by Django 4.1 on 2023-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_rsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsi',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
