# Generated by Django 4.1.7 on 2023-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('interval', models.CharField(max_length=5)),
                ('period', models.IntegerField(default=3)),
                ('infelicity', models.IntegerField(default=1)),
                ('value', models.IntegerField(default=0)),
                ('last_value', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('side', models.CharField(default='', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('first_ip', models.CharField(max_length=16)),
                ('requests', models.IntegerField(default=0)),
                ('ans_added', models.IntegerField(default=0)),
                ('ans_got', models.IntegerField(default=0)),
                ('subsription_lvl', models.CharField(default='blank', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
