# Generated by Django 4.1.7 on 2023-04-02 07:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^\\w+[\\w\\.\\-]+\\w+$')])),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\w+[\\w\\.\\-]+\\w+@([\\w\\-]+\\.)+\\w+$')])),
                ('password', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[\\w!@#$%^&*()+\\-=[\\]{};:\\\'",.<>/?]+$')])),
                ('password_hash', models.CharField(max_length=64)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(0, 'Active'), (10, 'Blocked'), (20, 'Dead')], default=0)),
                ('max_settings_count', models.PositiveIntegerField(default=5)),
                ('api_parameters', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('state', models.IntegerField(choices=[(0, 'Active'), (10, 'Disabled')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('api_class_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_value', models.FloatField(default=0)),
                ('stop_loss', models.FloatField(default=0)),
                ('take_profit', models.FloatField(default=0)),
                ('parameters', models.JSONField(default=dict)),
                ('label', models.CharField(default='Trading setting', max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='telegram_bot.client')),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='settings', to='telegram_bot.currencypair')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RSI', 'Rsi')], max_length=15)),
                ('parameters', models.JSONField(default=dict)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='telegram_bot.setting')),
            ],
        ),
        migrations.AddField(
            model_name='currencypair',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.service'),
        ),
    ]
