# Generated by Django 4.1.7 on 2023-03-21 05:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[\\w\\.\\-]+\\w+$')])),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w\\.\\-]+\\w+@([\\w\\-]+\\.)+\\w+$')])),
                ('password', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[\\w!@#$%^&*()+\\-=[\\]{};:\\\'",.<>/?]+$')])),
                ('password_hash', models.CharField(max_length=64)),
                ('last_login', models.DateTimeField()),
                ('state', models.IntegerField(choices=[(0, 'Active'), (10, 'Blocked'), (20, 'Dead')], default=0)),
                ('max_settings_count', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RSI', 'Rsi')], max_length=15)),
                ('parameters', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('api_class_name', models.CharField(max_length=25)),
                ('required_parameters', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_value', models.FloatField(default=0)),
                ('stop_loss', models.FloatField(default=0)),
                ('take_profit', models.FloatField(default=0)),
                ('parameters', models.JSONField(default=dict)),
                ('label', models.CharField(default='Trading setting', max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='telegram_bot.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Rsi',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='setting',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='settings', to='telegram_bot.currencypair'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='telegram_bot.setting'),
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.service'),
        ),
    ]
