# Generated by Django 4.1.7 on 2023-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
