# Generated by Django 4.1.7 on 2023-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_client_indicator_service_setting_delete_rsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='state',
            field=models.IntegerField(choices=[(0, 'Active'), (10, 'Disabled')], default=0),
        ),
    ]
