# Generated by Django 4.1.7 on 2023-04-02 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_client_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
