# Generated by Django 4.1 on 2023-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_rsi_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsi',
            name='updated',
        ),
        migrations.AlterField(
            model_name='rsi',
            name='side',
            field=models.CharField(default='', max_length=10),
        ),
    ]
